//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 01:20:04 PM CEST 
//


package com.wot.shared;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wot.shared package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WIKI_QNAME = new QName("http://wotachievement.appspot.com/", "WIKI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wot.shared
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlListCategoryAchievement }
     * 
     */
    public XmlListCategoryAchievement createXmlListCategoryAchievement() {
        return new XmlListCategoryAchievement();
    }

    /**
     * Create an instance of {@link XmlListSrcImg }
     * 
     */
    public XmlListSrcImg createXmlListSrcImg() {
        return new XmlListSrcImg();
    }

    /**
     * Create an instance of {@link XmlDescription }
     * 
     */
    public XmlDescription createXmlDescription() {
        return new XmlDescription();
    }

    /**
     * Create an instance of {@link XmlListAchievement }
     * 
     */
    public XmlListAchievement createXmlListAchievement() {
        return new XmlListAchievement();
    }

    /**
     * Create an instance of {@link XmlSrc }
     * 
     */
    public XmlSrc createXmlSrc() {
        return new XmlSrc();
    }

    /**
     * Create an instance of {@link XmlWiki }
     * 
     */
    public XmlWiki createXmlWiki() {
        return new XmlWiki();
    }

    /**
     * Create an instance of {@link XmlAchievements }
     * 
     */
    public XmlAchievements createXmlAchievements() {
        return new XmlAchievements();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlWiki }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wotachievement.appspot.com/", name = "WIKI")
    public JAXBElement<XmlWiki> createWIKI(XmlWiki value) {
        return new JAXBElement<XmlWiki>(_WIKI_QNAME, XmlWiki.class, null, value);
    }

}
