//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 01:20:04 PM CEST 
//


package com.wot.shared;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlListCategoryAchievement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlListCategoryAchievement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACHIEVEMENT" type="{http://wotachievement.appspot.com/}XmlListAchievement" maxOccurs="unbounded"/>
 *         &lt;element name="DESCRIPTION" type="{http://wotachievement.appspot.com/}XmlDescription"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlListCategoryAchievement", propOrder = {
    "achievement",
    "description"
})
public class XmlListCategoryAchievement implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -5344194589064445790L;
	@XmlElement(name = "ACHIEVEMENT", required = true)
    protected List<XmlListAchievement> achievement;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected XmlDescription description;
    @XmlAttribute(name = "NAME", required = true)
    protected String name;

    /**
     * Gets the value of the achievement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the achievement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACHIEVEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlListAchievement }
     * 
     * 
     */
    public List<XmlListAchievement> getACHIEVEMENT() {
        if (achievement == null) {
            achievement = new ArrayList<XmlListAchievement>();
        }
        return this.achievement;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDescription }
     *     
     */
    public XmlDescription getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDescription }
     *     
     */
    public void setDESCRIPTION(XmlDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

}
