//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 01:20:04 PM CEST 
//


package com.wot.shared;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlWiki complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlWiki">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ACHIEVEMENTS" type="{http://wotachievement.appspot.com/}XmlAchievements"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlWiki", propOrder = {
    "achievements"
})
@XmlRootElement
public class XmlWiki {

	
    @XmlElement(name = "ACHIEVEMENTS", required = true)
    protected XmlAchievements achievements;

    /**
     * Gets the value of the achievements property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAchievements }
     *     
     */
    public XmlAchievements getACHIEVEMENTS() {
        return achievements;
    }

    /**
     * Sets the value of the achievements property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAchievements }
     *     
     */
    public void setACHIEVEMENTS(XmlAchievements value) {
        this.achievements = value;
    }

}
